export const ErrorCode = {
  RPC_TIMEOUT: 'RPC_TIMEOUT',
  RPC_RATE_LIMITED: 'RPC_RATE_LIMITED',
  RPC_BLOCK_RANGE: 'RPC_BLOCK_RANGE',
  RPC_SERVER_ERROR: 'RPC_SERVER_ERROR',
  DB_CONNECTION: 'DB_CONNECTION',
  DB_WRITE_TIMEOUT: 'DB_WRITE_TIMEOUT',
  DECODE_ERROR: 'DECODE_ERROR',
  CONFIG_INVALID: 'CONFIG_INVALID',
  STELLAR_RETENTION: 'STELLAR_RETENTION',
  STELLAR_INVALID_CURSOR: 'STELLAR_INVALID_CURSOR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
